### ISSUE TITLE
Question about modifying assignedMembers

### ISSUE THREAD

**Issue by antista** [holaSpirit/holaspirit-docs#28]
https://github.com/holaSpirit/holaspirit-docs/blob/7f4b2dc25769d4f7ea81677b300ca04da36bb055/changelog.md?plain=1#L8

Hello! 
Could you please specify exactly which urls will be modified? I need to understand will the `assignedmembers` of `linked` in url `GET /organizations/{organization_id}/roles` be affected by the changes or this field will remain here?

**Comment by CorentinCresHola** [comment]
Hello :)
No, `GET /organizations/{organization_id}/roles` will not be affected by this modification and will still be returning `assignedMembers` in linked.

The only routes that will be affected by this modification are members endpoints : 

 - `GET /organizations/{organization_id}/members/{member_id}`
 -  ̀GET /public/organizations/{organization_public_slug}/members/{member_id}`

Have a good day !
Corentin
