### ISSUE TITLE
[07 February 2024] Removed `assignedMembers` from members serialization

### ISSUE THREAD

**Issue by CorentinCresHola** [holaSpirit/holaspirit-docs#29]
On 07 February 2024, we are modifying the GET `/api/organizations/{organization_id}/members/{member_id}` endpoint that will no longer serialize `assignedMembers`. (cf. https://github.com/holaSpirit/holaspirit-docs/blob/master/changelog.md)

## Affected endpoints

 - `GET /api/organizations/{organization_id}/members/{member_id}`

## Description

The affected endpoint will no longer serialize `data.assignedMembers` and `linked.assignedmembers`.

## Alternatives and recommandations

You can still find the assignations of a member through other endpoints, such as `GET /api/organizations/{organization_id}/roles?member={member_id}`.

Moreover, listing members through `GET /organizations/{organization_id}/members` or `GET /public/organizations/{organization_public_slug}/members` still serialize a `memberInRoles` attribute, that lists role identifiers this members is assigned to.

**Comment by jeanmonod** [comment]
Hi @CorentinCresHola,
This is an endpoint we are using. 2 times per day, we go through our 230 members to collect the role and the focus they have.
Just to be sure I get you right. I just have to move from `linked.assignedmembers` to `memberInRoles`? I will still be able to collect role id and focus?

**Comment by CorentinCresHola** [comment]
Hi,
No, you won't be able to access focus anymore using the `GET /api/orgnanizations/{organization_id}/members/{member_id}` endpoint. You will still be able to access its role ids (and only ids) through `memberInRoles`, we are not modifying this attribute.

However, since you need to access the member's focuses and roles, I'm encouraging you to use the `GET /api/orgnanizations/{organization_id}/roles?member={member_id}` endpoint : it will give you all the roles this member is assigned to (and since we are filtering by member, only these ones !) and you will have `assignedMembers` and `linked.assignedmembers` available here, hence the member's focuses. 

I hope everything is clearer, if you need any additional information please feel free to reach me again. :)

Have a nice day,
Corentin

**Comment by CorentinCresHola** [comment]
As a side note, you can send multiple ids to the `GET /api/orgnanizations/{organization_id}/roles?member={member1_id},{member2_id},{member3_id}`.

You will not be able to send the whole 230 member ids in a single request, since URL length has a limit (2048 chars), but you may batch it to your convenance.
